all:
	g++ hello.cpp -o hello.o

prueba:
	g++ hello.cpp -o papa.exe

bob:
	g++ alicebob_v1.cpp -o bob.o

alice:
	g++ alicebob_v2.cpp -o alice.o

# docker run -it --rm -v C:\dev\cursostec\estructuras:/home gcc bash