apiVersion: v1
kind: ConfigMap
metadata:
  name: mongodb-config
  labels:
    app: demobackend
data:
  # Logical service hostname for MongoDB (usually the Kubernetes Service name)
  mongo-serviceName: mongodbclusterservice
  # Default MongoDB port
  mongo-servicePort: 27017
  # Application database name
  mongo-database: demomongodb
  # Connection string without credentials (use a Secret for user/password)
  mongo-serviceUrl: mongodb://mongo:27017/app