federation_of_planets:
  target: dev
  outputs:
    dev:
      type: sqlserver
      driver: "ODBC Driver 18 for SQL Server"
      server: 192.168.5.166
      port: 1433
      database: federationofplanets
      schema: dbo
      username: "sa"
      password: "123456"
      trust_cert: true
      authentication: sql